### PR TITLE
Update GUI

### PR DESCRIPTION
**Pull request by lightningterror**
Add padding to MEM/GUP Max clock.
Should make the text inside the texbox a bit more readable.
Update release executable with the latest changes.

### CODE REVIEW

**Comment by mirh** [comment]
_starts to think it would be neater if you could just get writer privilege_

**Comment by lightningterror** [comment]
I don't mind , depends on @OneB1t tho.

I added a bit more fixes , can you check out how it is on your end ?

**Comment by mirh** [comment]
Sorry I only have GCN1

**Comment by lightningterror** [comment]
I was just asking for gui feedback , not to load a bios , tho you can load even if it's gcn1

**Pull request merged**
