### PR TITLE
Update release executable

### PR DESCRIPTION
**Pull request by lightningterror**
Update precompiled executable to latest version.

### CODE REVIEW

**Comment by mirh** [comment]
Can we just not put binaries in source control? 😪

**Comment by lightningterror** [comment]
Hmm people that don't want to compile the code download that executable.

**Comment by mirh** [comment]
*Yeees*, but good old guys at github thought to the "release" section for stuff like this.

**Comment by lightningterror** [comment]
True. @OneB1t should fix.

**Comment by mirh** [comment]
@OneB1t could you _actually_ actually fix it?

**Pull request merged**
